package com.hou.lift.model;

import java.util.Date;

public class TaskDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.task_detail_id
     *
     * @mbggenerated
     */
    private Integer taskDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.task_detail_name
     *
     * @mbggenerated
     */
    private String taskDetailName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.data_state
     *
     * @mbggenerated
     */
    private Integer dataState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.label_id
     *
     * @mbggenerated
     */
    private Integer labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_detail.grade_id
     *
     * @mbggenerated
     */
    private Integer gradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.task_detail_id
     *
     * @return the value of task_detail.task_detail_id
     *
     * @mbggenerated
     */
    public Integer getTaskDetailId() {
        return taskDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.task_detail_id
     *
     * @param taskDetailId the value for task_detail.task_detail_id
     *
     * @mbggenerated
     */
    public void setTaskDetailId(Integer taskDetailId) {
        this.taskDetailId = taskDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.user_id
     *
     * @return the value of task_detail.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.user_id
     *
     * @param userId the value for task_detail.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.task_id
     *
     * @return the value of task_detail.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.task_id
     *
     * @param taskId the value for task_detail.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.task_detail_name
     *
     * @return the value of task_detail.task_detail_name
     *
     * @mbggenerated
     */
    public String getTaskDetailName() {
        return taskDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.task_detail_name
     *
     * @param taskDetailName the value for task_detail.task_detail_name
     *
     * @mbggenerated
     */
    public void setTaskDetailName(String taskDetailName) {
        this.taskDetailName = taskDetailName == null ? null : taskDetailName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.data_state
     *
     * @return the value of task_detail.data_state
     *
     * @mbggenerated
     */
    public Integer getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.data_state
     *
     * @param dataState the value for task_detail.data_state
     *
     * @mbggenerated
     */
    public void setDataState(Integer dataState) {
        this.dataState = dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.create_time
     *
     * @return the value of task_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.create_time
     *
     * @param createTime the value for task_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.update_time
     *
     * @return the value of task_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.update_time
     *
     * @param updateTime the value for task_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.label_id
     *
     * @return the value of task_detail.label_id
     *
     * @mbggenerated
     */
    public Integer getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.label_id
     *
     * @param labelId the value for task_detail.label_id
     *
     * @mbggenerated
     */
    public void setLabelId(Integer labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_detail.grade_id
     *
     * @return the value of task_detail.grade_id
     *
     * @mbggenerated
     */
    public Integer getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_detail.grade_id
     *
     * @param gradeId the value for task_detail.grade_id
     *
     * @mbggenerated
     */
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }
}