package com.hou.lift.model;

import java.util.Date;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.begin_date
     *
     * @mbggenerated
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.label
     *
     * @mbggenerated
     */
    private Integer label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.grade
     *
     * @mbggenerated
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.total_detail
     *
     * @mbggenerated
     */
    private Integer totalDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.completed_detail
     *
     * @mbggenerated
     */
    private Integer completedDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.name
     *
     * @return the value of task.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.name
     *
     * @param name the value for task.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.user_id
     *
     * @return the value of task.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.user_id
     *
     * @param userId the value for task.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.begin_date
     *
     * @return the value of task.begin_date
     *
     * @mbggenerated
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.begin_date
     *
     * @param beginDate the value for task.begin_date
     *
     * @mbggenerated
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.label
     *
     * @return the value of task.label
     *
     * @mbggenerated
     */
    public Integer getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.label
     *
     * @param label the value for task.label
     *
     * @mbggenerated
     */
    public void setLabel(Integer label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.grade
     *
     * @return the value of task.grade
     *
     * @mbggenerated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.grade
     *
     * @param grade the value for task.grade
     *
     * @mbggenerated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.total_detail
     *
     * @return the value of task.total_detail
     *
     * @mbggenerated
     */
    public Integer getTotalDetail() {
        return totalDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.total_detail
     *
     * @param totalDetail the value for task.total_detail
     *
     * @mbggenerated
     */
    public void setTotalDetail(Integer totalDetail) {
        this.totalDetail = totalDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.completed_detail
     *
     * @return the value of task.completed_detail
     *
     * @mbggenerated
     */
    public Integer getCompletedDetail() {
        return completedDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.completed_detail
     *
     * @param completedDetail the value for task.completed_detail
     *
     * @mbggenerated
     */
    public void setCompletedDetail(Integer completedDetail) {
        this.completedDetail = completedDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_date
     *
     * @return the value of task.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_date
     *
     * @param createDate the value for task.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.update_date
     *
     * @return the value of task.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.update_date
     *
     * @param updateDate the value for task.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}