package com.hou.lift.dao;

import com.hou.lift.model.TaskDetail;
import com.hou.lift.model.TaskDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int countByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int deleteByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer taskDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int insert(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int insertSelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    List<TaskDetail> selectByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    TaskDetail selectByPrimaryKey(Integer taskDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskDetail record);
}